
CREATE TABLE callouts (
id INTEGER NOT NULL AUTO_INCREMENT,
series INTEGER NOT NULL,
number VARCHAR(12) NOT NULL,
inuse INTEGER NOT NULL DEFAULT 0,
answered INTEGER NOT NULL DEFAULT 0,
tries INTEGER NOT NULL DEFAULT 0,
lasttry VARCHAR(80) NOT NULL DEFAULT '',
PRIMARY KEY  (`id`)
);

CREATE TABLE series (
id INTEGER NOT NULL AUTO_INCREMENT,
customer INTEGER NOT NULL,
clidname VARCHAR(80) NOT NULL DEFAULT '',
clidnumber VARCHAR(80) NOT NULL DEFAULT '',
starthour INTEGER NOT NULL DEFAULT 0,
endhour INTEGER NOT NULL DEFAULT 0,
Sun INTEGER NOT NULL DEFAULT 0,
Mon INTEGER NOT NULL DEFAULT 0,
Tue INTEGER NOT NULL DEFAULT 0,
Wed INTEGER NOT NULL DEFAULT 0,
Thu INTEGER NOT NULL DEFAULT 0,
Fri INTEGER NOT NULL DEFAULT 0,
Sat INTEGER NOT NULL DEFAULT 0,
try_times INTEGER NOT NULL DEFAULT 3,
external_extension VARCHAR(40) NOT NULL DEFAULT '',
external_context VARCHAR(40) NOT NULL DEFAULT '',
sound_file VARCHAR(60) NOT NULL DEFAULT '',
creation TIMESTAMP NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
status INTEGER NOT NULL DEFAULT 0,
email VARCHAR(80) NOT NULL DEFAULT '',
description VARCHAR(255) NOT NULL DEFAULT '',
PRIMARY KEY  (`id`)
);

CREATE TABLE customers (
id INTEGER NOT NULL AUTO_INCREMENT,
accountcode VARCHAR(80) NOT NULL DEFAULT '',
PRIMARY KEY  (`id`)
);
