CREATE DATABASE IF NOT EXISTS survey;

use survey;

CREATE TABLE surveys (id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
inuse INTEGER NOT NULL DEFAULT 0,
leaving VARCHAR(60),
error_leaving VARCHAR(60),
total_questions INTEGER NOT NULL DEFAULT 1);

CREATE TABLE responses (id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
survey_id INTEGER NOT NULL,
question INTEGER NOT NULL,
date CHAR(40) NOT NULL DEFAULT '',
callerid VARCHAR( 50 ) NULL,
answer INTEGER NOT NULL);

CREATE TABLE questions(id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
survey_id INTEGER NOT NULL,
question_number INTEGER NOT NULL,
min_valid INTEGER NOT NULL,
max_valid INTEGER NOT NULL,
sound_file VARCHAR(60));
 
