-- -----------Configuration - Purge - "Invoices" spelling is wrong displayed query. Date of change : 160920 change_by : Bhargav 

UPDATE `system` SET `display_name` = 'Invoices Older Than Days' WHERE `system`.`name` = "purge_invoices";

-- -------------------------------------2021-04-15

INSERT INTO `menu_modules` (`menu_label`, `module_name`, `module_url`, `menu_title`, `menu_image`, `menu_subtitle`, `priority`) VALUES
('Timezone', 'systems', 'systems/timezone_list/', 'Configuration', '', '0', 90.7);

update userlevels set module_permissions = concat( module_permissions, ',', ( SELECT max(
id ) FROM menu_modules ) ) WHERE userlevelid = -1;

DROP TABLE IF EXISTS `timezone`;

CREATE TABLE `timezone` (
  `id` int NOT NULL AUTO_INCREMENT,
  `gmttime` varchar(255) DEFAULT NULL,
  `gmtoffset` bigint NOT NULL DEFAULT '0',
  `timezone_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `timezone_digit` varchar(60) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `timezone` (`id`, `gmttime`, `gmtoffset`, `timezone_name`, `timezone_digit`) VALUES
(NULL, 'GMT+01:00', 3600, 'Europe/Andorra', '1'),
(NULL, 'GMT+04:00', 14400, 'Asia/Dubai', '4'),
(NULL, 'GMT+04:30', 16200, 'Asia/Kabul', '4'),
(NULL, 'GMT-04:00', -14400, 'America/Antigua', '-4'),
(NULL, 'GMT-04:00', -14400, 'America/Anguilla', '-4'),
(NULL, 'GMT+01:00', 3600, 'Europe/Tirane', '1'),
(NULL, 'GMT+04:00', 14400, 'Asia/Yerevan', '4'),
(NULL, 'GMT+01:00', 3600, 'Africa/Luanda', '1'),
(NULL, 'GMT+11:00', 39600, 'Antarctica/Casey', '11'),
(NULL, 'GMT+07:00', 25200, 'Antarctica/Davis', '7'),
(NULL, 'GMT+10:00', 36000, 'Antarctica/DumontDUrville', '10'),
(NULL, 'GMT+05:00', 18000, 'Antarctica/Mawson', '5'),
(NULL, 'GMT+13:00', 46800, 'Antarctica/McMurdo', '13'),
(NULL, 'GMT-03:00', -10800, 'Antarctica/Palmer', '-3'),
(NULL, 'GMT-03:00', -10800, 'Antarctica/Rothera', '-3'),
(NULL, 'GMT+03:00', 10800, 'Antarctica/Syowa', '3'),
(NULL, 'GMT+00:00', 0, 'Antarctica/Troll', '0'),
(NULL, 'GMT+06:00', 21600, 'Antarctica/Vostok', '6'),
(NULL, 'GMT-03:00', -10800, 'America/Argentina/Buenos_Aires', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Argentina/Catamarca', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Argentina/Cordoba', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Argentina/Jujuy', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Argentina/La_Rioja', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Argentina/Mendoza', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Argentina/Rio_Gallegos', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Argentina/Salta', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Argentina/San_Juan', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Argentina/San_Luis', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Argentina/Tucuman', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Argentina/Ushuaia', '-3'),
(NULL, 'GMT-11:00', -39600, 'Pacific/Pago_Pago', '-11'),
(NULL, 'GMT+01:00', 3600, 'Europe/Vienna', '1'),
(NULL, 'GMT+11:00', 39600, 'Antarctica/Macquarie', '11'),
(NULL, 'GMT+10:30', 37800, 'Australia/Adelaide', '10'),
(NULL, 'GMT+10:00', 36000, 'Australia/Brisbane', '10'),
(NULL, 'GMT+10:30', 37800, 'Australia/Broken_Hill', '10'),
(NULL, 'GMT+11:00', 39600, 'Australia/Currie', '11'),
(NULL, 'GMT+09:30', 34200, 'Australia/Darwin', '9'),
(NULL, 'GMT+08:45', 31500, 'Australia/Eucla', '8'),
(NULL, 'GMT+11:00', 39600, 'Australia/Hobart', '11'),
(NULL, 'GMT+10:00', 36000, 'Australia/Lindeman', '10'),
(NULL, 'GMT+11:00', 39600, 'Australia/Lord_Howe', '11'),
(NULL, 'GMT+11:00', 39600, 'Australia/Melbourne', '11'),
(NULL, 'GMT+08:00', 28800, 'Australia/Perth', '8'),
(NULL, 'GMT+11:00', 39600, 'Australia/Sydney', '11'),
(NULL, 'GMT-04:00', -14400, 'America/Aruba', '-4'),
(NULL, 'GMT+02:00', 7200, 'Europe/Mariehamn', '2'),
(NULL, 'GMT+04:00', 14400, 'Asia/Baku', '4'),
(NULL, 'GMT+01:00', 3600, 'Europe/Sarajevo', '1'),
(NULL, 'GMT-04:00', -14400, 'America/Barbados', '-4'),
(NULL, 'GMT+06:00', 21600, 'Asia/Dhaka', '6'),
(NULL, 'GMT+01:00', 3600, 'Europe/Brussels', '1'),
(NULL, 'GMT+00:00', 0, 'Africa/Ouagadougou', '0'),
(NULL, 'GMT+02:00', 7200, 'Europe/Sofia', '2'),
(NULL, 'GMT+03:00', 10800, 'Asia/Bahrain', '3'),
(NULL, 'GMT+02:00', 7200, 'Africa/Bujumbura', '2'),
(NULL, 'GMT+01:00', 3600, 'Africa/Porto-Novo', '1'),
(NULL, 'GMT-04:00', -14400, 'America/St_Barthelemy', '-4'),
(NULL, 'GMT-04:00', -14400, 'Atlantic/Bermuda', '-4'),
(NULL, 'GMT+08:00', 28800, 'Asia/Brunei', '8'),
(NULL, 'GMT-04:00', -14400, 'America/La_Paz', '-4'),
(NULL, 'GMT-04:00', -14400, 'America/Kralendijk', '-4'),
(NULL, 'GMT-03:00', -10800, 'America/Araguaina', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Bahia', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Belem', '-3'),
(NULL, 'GMT-04:00', -14400, 'America/Boa_Vista', '-4'),
(NULL, 'GMT-04:00', -14400, 'America/Campo_Grande', '-4'),
(NULL, 'GMT-04:00', -14400, 'America/Cuiaba', '-4'),
(NULL, 'GMT-05:00', -18000, 'America/Eirunepe', '-5'),
(NULL, 'GMT-03:00', -10800, 'America/Fortaleza', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Maceio', '-3'),
(NULL, 'GMT-04:00', -14400, 'America/Manaus', '-4'),
(NULL, 'GMT-02:00', -7200, 'America/Noronha', '-2'),
(NULL, 'GMT-04:00', -14400, 'America/Porto_Velho', '-4'),
(NULL, 'GMT-03:00', -10800, 'America/Recife', '-3'),
(NULL, 'GMT-05:00', -18000, 'America/Rio_Branco', '-5'),
(NULL, 'GMT-03:00', -10800, 'America/Santarem', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Sao_Paulo', '-3'),
(NULL, 'GMT-05:00', -18000, 'America/Nassau', '-5'),
(NULL, 'GMT+06:00', 21600, 'Asia/Thimphu', '6'),
(NULL, 'GMT+02:00', 7200, 'Africa/Gaborone', '2'),
(NULL, 'GMT+03:00', 10800, 'Europe/Minsk', '3'),
(NULL, 'GMT-06:00', -21600, 'America/Belize', '-6'),
(NULL, 'GMT-05:00', -18000, 'America/Atikokan', '-5'),
(NULL, 'GMT-04:00', -14400, 'America/Blanc-Sablon', '-4'),
(NULL, 'GMT-07:00', -25200, 'America/Cambridge_Bay', '-7'),
(NULL, 'GMT-07:00', -25200, 'America/Creston', '-7'),
(NULL, 'GMT-07:00', -25200, 'America/Dawson', '-7'),
(NULL, 'GMT-07:00', -25200, 'America/Dawson_Creek', '-7'),
(NULL, 'GMT-07:00', -25200, 'America/Edmonton', '-7'),
(NULL, 'GMT-07:00', -25200, 'America/Fort_Nelson', '-7'),
(NULL, 'GMT-04:00', -14400, 'America/Glace_Bay', '-4'),
(NULL, 'GMT-04:00', -14400, 'America/Goose_Bay', '-4'),
(NULL, 'GMT-04:00', -14400, 'America/Halifax', '-4'),
(NULL, 'GMT-07:00', -25200, 'America/Inuvik', '-7'),
(NULL, 'GMT-05:00', -18000, 'America/Iqaluit', '-5'),
(NULL, 'GMT-04:00', -14400, 'America/Moncton', '-4'),
(NULL, 'GMT-05:00', -18000, 'America/Nipigon', '-5'),
(NULL, 'GMT-05:00', -18000, 'America/Pangnirtung', '-5'),
(NULL, 'GMT-06:00', -21600, 'America/Rainy_River', '-6'),
(NULL, 'GMT-06:00', -21600, 'America/Rankin_Inlet', '-6'),
(NULL, 'GMT-06:00', -21600, 'America/Regina', '-6'),
(NULL, 'GMT-06:00', -21600, 'America/Resolute', '-6'),
(NULL, 'GMT-03:30', -12600, 'America/St_Johns', '-4'),
(NULL, 'GMT-06:00', -21600, 'America/Swift_Current', '-6'),
(NULL, 'GMT-05:00', -18000, 'America/Thunder_Bay', '-5'),
(NULL, 'GMT-05:00', -18000, 'America/Toronto', '-5'),
(NULL, 'GMT-08:00', -28800, 'America/Vancouver', '-8'),
(NULL, 'GMT-07:00', -25200, 'America/Whitehorse', '-7'),
(NULL, 'GMT-06:00', -21600, 'America/Winnipeg', '-6'),
(NULL, 'GMT-07:00', -25200, 'America/Yellowknife', '-7'),
(NULL, 'GMT+06:30', 23400, 'Indian/Cocos', '6'),
(NULL, 'GMT+01:00', 3600, 'Africa/Kinshasa', '1'),
(NULL, 'GMT+02:00', 7200, 'Africa/Lubumbashi', '2'),
(NULL, 'GMT+01:00', 3600, 'Africa/Bangui', '1'),
(NULL, 'GMT+01:00', 3600, 'Africa/Brazzaville', '1'),
(NULL, 'GMT+01:00', 3600, 'Europe/Zurich', '1'),
(NULL, 'GMT+00:00', 0, 'Africa/Abidjan', '0'),
(NULL, 'GMT-10:00', -36000, 'Pacific/Rarotonga', '-10'),
(NULL, 'GMT-03:00', -10800, 'America/Punta_Arenas', '-3'),
(NULL, 'GMT-03:00', -10800, 'America/Santiago', '-3'),
(NULL, 'GMT-05:00', -18000, 'Pacific/Easter', '-5'),
(NULL, 'GMT+01:00', 3600, 'Africa/Douala', '1'),
(NULL, 'GMT+08:00', 28800, 'Asia/Shanghai', '8'),
(NULL, 'GMT+06:00', 21600, 'Asia/Urumqi', '6'),
(NULL, 'GMT-05:00', -18000, 'America/Bogota', '-5'),
(NULL, 'GMT-06:00', -21600, 'America/Costa_Rica', '-6'),
(NULL, 'GMT-05:00', -18000, 'America/Havana', '-5'),
(NULL, 'GMT-01:00', -3600, 'Atlantic/Cape_Verde', '-1'),
(NULL, 'GMT-04:00', -14400, 'America/Curacao', '-4'),
(NULL, 'GMT+07:00', 25200, 'Indian/Christmas', '7'),
(NULL, 'GMT+02:00', 7200, 'Asia/Famagusta', '2'),
(NULL, 'GMT+02:00', 7200, 'Asia/Nicosia', '2'),
(NULL, 'GMT+01:00', 3600, 'Europe/Prague', '1'),
(NULL, 'GMT+01:00', 3600, 'Europe/Berlin', '1'),
(NULL, 'GMT+01:00', 3600, 'Europe/Busingen', '1'),
(NULL, 'GMT+03:00', 10800, 'Africa/Djibouti', '3'),
(NULL, 'GMT+01:00', 3600, 'Europe/Copenhagen', '1'),
(NULL, 'GMT-04:00', -14400, 'America/Dominica', '-4'),
(NULL, 'GMT-04:00', -14400, 'America/Santo_Domingo', '-4'),
(NULL, 'GMT+01:00', 3600, 'Africa/Algiers', '1'),
(NULL, 'GMT-05:00', -18000, 'America/Guayaquil', '-5'),
(NULL, 'GMT-06:00', -21600, 'Pacific/Galapagos', '-6'),
(NULL, 'GMT+02:00', 7200, 'Europe/Tallinn', '2'),
(NULL, 'GMT+02:00', 7200, 'Africa/Cairo', '2'),
(NULL, 'GMT+01:00', 3600, 'Africa/El_Aaiun', '1'),
(NULL, 'GMT+03:00', 10800, 'Africa/Asmara', '3'),
(NULL, 'GMT+01:00', 3600, 'Africa/Ceuta', '1'),
(NULL, 'GMT+00:00', 0, 'Atlantic/Canary', '0'),
(NULL, 'GMT+01:00', 3600, 'Europe/Madrid', '1'),
(NULL, 'GMT+03:00', 10800, 'Africa/Addis_Ababa', '3'),
(NULL, 'GMT+02:00', 7200, 'Europe/Helsinki', '2'),
(NULL, 'GMT+13:00', 46800, 'Pacific/Fiji', '13'),
(NULL, 'GMT-03:00', -10800, 'Atlantic/Stanley', '-3'),
(NULL, 'GMT+10:00', 36000, 'Pacific/Chuuk', '10'),
(NULL, 'GMT+11:00', 39600, 'Pacific/Kosrae', '11'),
(NULL, 'GMT+11:00', 39600, 'Pacific/Pohnpei', '11'),
(NULL, 'GMT+00:00', 0, 'Atlantic/Faroe', '0'),
(NULL, 'GMT+01:00', 3600, 'Europe/Paris', '1'),
(NULL, 'GMT+01:00', 3600, 'Africa/Libreville', '1'),
(NULL, 'GMT+00:00', 0, 'Europe/London', '0'),
(NULL, 'GMT-04:00', -14400, 'America/Grenada', '-4'),
(NULL, 'GMT+04:00', 14400, 'Asia/Tbilisi', '4'),
(NULL, 'GMT-03:00', -10800, 'America/Cayenne', '-3'),
(NULL, 'GMT+00:00', 0, 'Europe/Guernsey', '0'),
(NULL, 'GMT+00:00', 0, 'Africa/Accra', '0'),
(NULL, 'GMT+01:00', 3600, 'Europe/Gibraltar', '1'),
(NULL, 'GMT+00:00', 0, 'America/Danmarkshavn', '0'),
(NULL, 'GMT-03:00', -10800, 'America/Nuuk', '-3'),
(NULL, 'GMT-01:00', -3600, 'America/Scoresbysund', '-1'),
(NULL, 'GMT-04:00', -14400, 'America/Thule', '-4'),
(NULL, 'GMT+00:00', 0, 'Africa/Banjul', '0'),
(NULL, 'GMT+00:00', 0, 'Africa/Conakry', '0'),
(NULL, 'GMT-04:00', -14400, 'America/Guadeloupe', '-4'),
(NULL, 'GMT+01:00', 3600, 'Africa/Malabo', '1'),
(NULL, 'GMT+02:00', 7200, 'Europe/Athens', '2'),
(NULL, 'GMT-02:00', -7200, 'Atlantic/South_Georgia', '-2'),
(NULL, 'GMT-06:00', -21600, 'America/Guatemala', '-6'),
(NULL, 'GMT+10:00', 36000, 'Pacific/Guam', '10'),
(NULL, 'GMT+00:00', 0, 'Africa/Bissau', '0'),
(NULL, 'GMT-04:00', -14400, 'America/Guyana', '-4'),
(NULL, 'GMT+08:00', 28800, 'Asia/Hong_Kong', '8'),
(NULL, 'GMT-06:00', -21600, 'America/Tegucigalpa', '-6'),
(NULL, 'GMT+01:00', 3600, 'Europe/Zagreb', '1'),
(NULL, 'GMT-05:00', -18000, 'America/Port-au-Prince', '-5'),
(NULL, 'GMT+01:00', 3600, 'Europe/Budapest', '1'),
(NULL, 'GMT+07:00', 25200, 'Asia/Jakarta', '7'),
(NULL, 'GMT+09:00', 32400, 'Asia/Jayapura', '9'),
(NULL, 'GMT+08:00', 28800, 'Asia/Makassar', '8'),
(NULL, 'GMT+07:00', 25200, 'Asia/Pontianak', '7'),
(NULL, 'GMT+00:00', 0, 'Europe/Dublin', '0'),
(NULL, 'GMT+02:00', 7200, 'Asia/Jerusalem', '2'),
(NULL, 'GMT+00:00', 0, 'Europe/Isle_of_Man', '0'),
(NULL, 'GMT+05:30', 19800, 'Asia/Kolkata', '5'),
(NULL, 'GMT+06:00', 21600, 'Indian/Chagos', '6'),
(NULL, 'GMT+03:00', 10800, 'Asia/Baghdad', '3'),
(NULL, 'GMT+03:30', 12600, 'Asia/Tehran', '3'),
(NULL, 'GMT+00:00', 0, 'Atlantic/Reykjavik', '0'),
(NULL, 'GMT+01:00', 3600, 'Europe/Rome', '1'),
(NULL, 'GMT+00:00', 0, 'Europe/Jersey', '0'),
(NULL, 'GMT-05:00', -18000, 'America/Jamaica', '-5'),
(NULL, 'GMT+02:00', 7200, 'Asia/Amman', '2'),
(NULL, 'GMT+09:00', 32400, 'Asia/Tokyo', '9'),
(NULL, 'GMT+03:00', 10800, 'Africa/Nairobi', '3'),
(NULL, 'GMT+06:00', 21600, 'Asia/Bishkek', '6'),
(NULL, 'GMT+07:00', 25200, 'Asia/Phnom_Penh', '7'),
(NULL, 'GMT+13:00', 46800, 'Pacific/Enderbury', '13'),
(NULL, 'GMT+14:00', 50400, 'Pacific/Kiritimati', '14'),
(NULL, 'GMT+12:00', 43200, 'Pacific/Tarawa', '12'),
(NULL, 'GMT+03:00', 10800, 'Indian/Comoro', '3'),
(NULL, 'GMT-04:00', -14400, 'America/St_Kitts', '-4'),
(NULL, 'GMT+09:00', 32400, 'Asia/Pyongyang', '9'),
(NULL, 'GMT+09:00', 32400, 'Asia/Seoul', '9'),
(NULL, 'GMT+03:00', 10800, 'Asia/Kuwait', '3'),
(NULL, 'GMT-05:00', -18000, 'America/Cayman', '-5'),
(NULL, 'GMT+06:00', 21600, 'Asia/Almaty', '6'),
(NULL, 'GMT+05:00', 18000, 'Asia/Aqtau', '5'),
(NULL, 'GMT+05:00', 18000, 'Asia/Aqtobe', '5'),
(NULL, 'GMT+05:00', 18000, 'Asia/Atyrau', '5'),
(NULL, 'GMT+05:00', 18000, 'Asia/Oral', '5'),
(NULL, 'GMT+06:00', 21600, 'Asia/Qostanay', '6'),
(NULL, 'GMT+05:00', 18000, 'Asia/Qyzylorda', '5'),
(NULL, 'GMT+07:00', 25200, 'Asia/Vientiane', '7'),
(NULL, 'GMT+02:00', 7200, 'Asia/Beirut', '2'),
(NULL, 'GMT-04:00', -14400, 'America/St_Lucia', '-4'),
(NULL, 'GMT+01:00', 3600, 'Europe/Vaduz', '1'),
(NULL, 'GMT+05:30', 19800, 'Asia/Colombo', '5'),
(NULL, 'GMT+00:00', 0, 'Africa/Monrovia', '0'),
(NULL, 'GMT+02:00', 7200, 'Africa/Maseru', '2'),
(NULL, 'GMT+02:00', 7200, 'Europe/Vilnius', '2'),
(NULL, 'GMT+01:00', 3600, 'Europe/Luxembourg', '1'),
(NULL, 'GMT+02:00', 7200, 'Europe/Riga', '2'),
(NULL, 'GMT+02:00', 7200, 'Africa/Tripoli', '2'),
(NULL, 'GMT+01:00', 3600, 'Africa/Casablanca', '1'),
(NULL, 'GMT+01:00', 3600, 'Europe/Monaco', '1'),
(NULL, 'GMT+02:00', 7200, 'Europe/Chisinau', '2'),
(NULL, 'GMT+01:00', 3600, 'Europe/Podgorica', '1'),
(NULL, 'GMT-04:00', -14400, 'America/Marigot', '-4'),
(NULL, 'GMT+03:00', 10800, 'Indian/Antananarivo', '3'),
(NULL, 'GMT+12:00', 43200, 'Pacific/Kwajalein', '12'),
(NULL, 'GMT+12:00', 43200, 'Pacific/Majuro', '12'),
(NULL, 'GMT+01:00', 3600, 'Europe/Skopje', '1'),
(NULL, 'GMT+00:00', 0, 'Africa/Bamako', '0'),
(NULL, 'GMT+06:30', 23400, 'Asia/Yangon', '6'),
(NULL, 'GMT+08:00', 28800, 'Asia/Choibalsan', '8'),
(NULL, 'GMT+07:00', 25200, 'Asia/Hovd', '7'),
(NULL, 'GMT+08:00', 28800, 'Asia/Ulaanbaatar', '8'),
(NULL, 'GMT+08:00', 28800, 'Asia/Macau', '8'),
(NULL, 'GMT+10:00', 36000, 'Pacific/Saipan', '10'),
(NULL, 'GMT-04:00', -14400, 'America/Martinique', '-4'),
(NULL, 'GMT+00:00', 0, 'Africa/Nouakchott', '0'),
(NULL, 'GMT-04:00', -14400, 'America/Montserrat', '-4'),
(NULL, 'GMT+01:00', 3600, 'Europe/Malta', '1'),
(NULL, 'GMT+04:00', 14400, 'Indian/Mauritius', '4'),
(NULL, 'GMT+05:00', 18000, 'Indian/Maldives', '5'),
(NULL, 'GMT+02:00', 7200, 'Africa/Blantyre', '2'),
(NULL, 'GMT-06:00', -21600, 'America/Bahia_Banderas', '-6'),
(NULL, 'GMT-05:00', -18000, 'America/Cancun', '-5'),
(NULL, 'GMT-07:00', -25200, 'America/Chihuahua', '-7'),
(NULL, 'GMT-07:00', -25200, 'America/Hermosillo', '-7'),
(NULL, 'GMT-06:00', -21600, 'America/Matamoros', '-6'),
(NULL, 'GMT-07:00', -25200, 'America/Mazatlan', '-7'),
(NULL, 'GMT-06:00', -21600, 'America/Merida', '-6'),
(NULL, 'GMT-06:00', -21600, 'America/Mexico_City', '-6'),
(NULL, 'GMT-06:00', -21600, 'America/Monterrey', '-6'),
(NULL, 'GMT-07:00', -25200, 'America/Ojinaga', '-7'),
(NULL, 'GMT-08:00', -28800, 'America/Tijuana', '-8'),
(NULL, 'GMT+08:00', 28800, 'Asia/Kuala_Lumpur', '8'),
(NULL, 'GMT+08:00', 28800, 'Asia/Kuching', '8'),
(NULL, 'GMT+02:00', 7200, 'Africa/Maputo', '2'),
(NULL, 'GMT+02:00', 7200, 'Africa/Windhoek', '2'),
(NULL, 'GMT+11:00', 39600, 'Pacific/Noumea', '11'),
(NULL, 'GMT+01:00', 3600, 'Africa/Niamey', '1'),
(NULL, 'GMT+12:00', 43200, 'Pacific/Norfolk', '12'),
(NULL, 'GMT+01:00', 3600, 'Africa/Lagos', '1'),
(NULL, 'GMT-06:00', -21600, 'America/Managua', '-6'),
(NULL, 'GMT+01:00', 3600, 'Europe/Amsterdam', '1'),
(NULL, 'GMT+01:00', 3600, 'Europe/Oslo', '1'),
(NULL, 'GMT+05:45', 20700, 'Asia/Kathmandu', '5'),
(NULL, 'GMT+12:00', 43200, 'Pacific/Nauru', '12'),
(NULL, 'GMT-11:00', -39600, 'Pacific/Niue', '-11'),
(NULL, 'GMT+13:00', 46800, 'Pacific/Auckland', '13'),
(NULL, 'GMT+13:45', 49500, 'Pacific/Chatham', '13'),
(NULL, 'GMT+04:00', 14400, 'Asia/Muscat', '4'),
(NULL, 'GMT-05:00', -18000, 'America/Panama', '-5'),
(NULL, 'GMT-05:00', -18000, 'America/Lima', '-5'),
(NULL, 'GMT-09:00', -32400, 'Pacific/Gambier', '-9'),
(NULL, 'GMT-09:30', -34200, 'Pacific/Marquesas', '-10'),
(NULL, 'GMT-10:00', -36000, 'Pacific/Tahiti', '-10'),
(NULL, 'GMT+11:00', 39600, 'Pacific/Bougainville', '11'),
(NULL, 'GMT+10:00', 36000, 'Pacific/Port_Moresby', '10'),
(NULL, 'GMT+08:00', 28800, 'Asia/Manila', '8'),
(NULL, 'GMT+05:00', 18000, 'Asia/Karachi', '5'),
(NULL, 'GMT+01:00', 3600, 'Europe/Warsaw', '1'),
(NULL, 'GMT-03:00', -10800, 'America/Miquelon', '-3'),
(NULL, 'GMT-08:00', -28800, 'Pacific/Pitcairn', '-8'),
(NULL, 'GMT-04:00', -14400, 'America/Puerto_Rico', '-4'),
(NULL, 'GMT+02:00', 7200, 'Asia/Gaza', '2'),
(NULL, 'GMT+02:00', 7200, 'Asia/Hebron', '2'),
(NULL, 'GMT-01:00', -3600, 'Atlantic/Azores', '-1'),
(NULL, 'GMT+00:00', 0, 'Atlantic/Madeira', '0'),
(NULL, 'GMT+00:00', 0, 'Europe/Lisbon', '0'),
(NULL, 'GMT+09:00', 32400, 'Pacific/Palau', '9'),
(NULL, 'GMT-03:00', -10800, 'America/Asuncion', '-3'),
(NULL, 'GMT+03:00', 10800, 'Asia/Qatar', '3'),
(NULL, 'GMT+04:00', 14400, 'Indian/Reunion', '4'),
(NULL, 'GMT+02:00', 7200, 'Europe/Bucharest', '2'),
(NULL, 'GMT+01:00', 3600, 'Europe/Belgrade', '1'),
(NULL, 'GMT+12:00', 43200, 'Asia/Anadyr', '12'),
(NULL, 'GMT+07:00', 25200, 'Asia/Barnaul', '7'),
(NULL, 'GMT+09:00', 32400, 'Asia/Chita', '9'),
(NULL, 'GMT+08:00', 28800, 'Asia/Irkutsk', '8'),
(NULL, 'GMT+12:00', 43200, 'Asia/Kamchatka', '12'),
(NULL, 'GMT+09:00', 32400, 'Asia/Khandyga', '9'),
(NULL, 'GMT+07:00', 25200, 'Asia/Krasnoyarsk', '7'),
(NULL, 'GMT+11:00', 39600, 'Asia/Magadan', '11'),
(NULL, 'GMT+07:00', 25200, 'Asia/Novokuznetsk', '7'),
(NULL, 'GMT+07:00', 25200, 'Asia/Novosibirsk', '7'),
(NULL, 'GMT+06:00', 21600, 'Asia/Omsk', '6'),
(NULL, 'GMT+11:00', 39600, 'Asia/Sakhalin', '11'),
(NULL, 'GMT+11:00', 39600, 'Asia/Srednekolymsk', '11'),
(NULL, 'GMT+07:00', 25200, 'Asia/Tomsk', '7'),
(NULL, 'GMT+10:00', 36000, 'Asia/Ust-Nera', '10'),
(NULL, 'GMT+10:00', 36000, 'Asia/Vladivostok', '10'),
(NULL, 'GMT+09:00', 32400, 'Asia/Yakutsk', '9'),
(NULL, 'GMT+05:00', 18000, 'Asia/Yekaterinburg', '5'),
(NULL, 'GMT+04:00', 14400, 'Europe/Astrakhan', '4'),
(NULL, 'GMT+02:00', 7200, 'Europe/Kaliningrad', '2'),
(NULL, 'GMT+03:00', 10800, 'Europe/Kirov', '3'),
(NULL, 'GMT+03:00', 10800, 'Europe/Moscow', '3'),
(NULL, 'GMT+04:00', 14400, 'Europe/Samara', '4'),
(NULL, 'GMT+04:00', 14400, 'Europe/Saratov', '4'),
(NULL, 'GMT+04:00', 14400, 'Europe/Ulyanovsk', '4'),
(NULL, 'GMT+03:00', 10800, 'Europe/Volgograd', '3'),
(NULL, 'GMT+02:00', 7200, 'Africa/Kigali', '2'),
(NULL, 'GMT+03:00', 10800, 'Asia/Riyadh', '3'),
(NULL, 'GMT+11:00', 39600, 'Pacific/Guadalcanal', '11'),
(NULL, 'GMT+04:00', 14400, 'Indian/Mahe', '4'),
(NULL, 'GMT+02:00', 7200, 'Africa/Khartoum', '2'),
(NULL, 'GMT+01:00', 3600, 'Europe/Stockholm', '1'),
(NULL, 'GMT+08:00', 28800, 'Asia/Singapore', '8'),
(NULL, 'GMT+00:00', 0, 'Atlantic/St_Helena', '0'),
(NULL, 'GMT+01:00', 3600, 'Europe/Ljubljana', '1'),
(NULL, 'GMT+01:00', 3600, 'Arctic/Longyearbyen', '1'),
(NULL, 'GMT+01:00', 3600, 'Europe/Bratislava', '1'),
(NULL, 'GMT+00:00', 0, 'Africa/Freetown', '0'),
(NULL, 'GMT+01:00', 3600, 'Europe/San_Marino', '1'),
(NULL, 'GMT+00:00', 0, 'Africa/Dakar', '0'),
(NULL, 'GMT+03:00', 10800, 'Africa/Mogadishu', '3'),
(NULL, 'GMT-03:00', -10800, 'America/Paramaribo', '-3'),
(NULL, 'GMT+03:00', 10800, 'Africa/Juba', '3'),
(NULL, 'GMT+00:00', 0, 'Africa/Sao_Tome', '0'),
(NULL, 'GMT-06:00', -21600, 'America/El_Salvador', '-6'),
(NULL, 'GMT-04:00', -14400, 'America/Lower_Princes', '-4'),
(NULL, 'GMT+02:00', 7200, 'Asia/Damascus', '2'),
(NULL, 'GMT+02:00', 7200, 'Africa/Mbabane', '2'),
(NULL, 'GMT-05:00', -18000, 'America/Grand_Turk', '-5'),
(NULL, 'GMT+01:00', 3600, 'Africa/Ndjamena', '1'),
(NULL, 'GMT+05:00', 18000, 'Indian/Kerguelen', '5'),
(NULL, 'GMT+00:00', 0, 'Africa/Lome', '0'),
(NULL, 'GMT+07:00', 25200, 'Asia/Bangkok', '7'),
(NULL, 'GMT+05:00', 18000, 'Asia/Dushanbe', '5'),
(NULL, 'GMT+13:00', 46800, 'Pacific/Fakaofo', '13'),
(NULL, 'GMT+09:00', 32400, 'Asia/Dili', '9'),
(NULL, 'GMT+05:00', 18000, 'Asia/Ashgabat', '5'),
(NULL, 'GMT+01:00', 3600, 'Africa/Tunis', '1'),
(NULL, 'GMT+13:00', 46800, 'Pacific/Tongatapu', '13'),
(NULL, 'GMT+03:00', 10800, 'Europe/Istanbul', '3'),
(NULL, 'GMT-04:00', -14400, 'America/Port_of_Spain', '-4'),
(NULL, 'GMT+12:00', 43200, 'Pacific/Funafuti', '12'),
(NULL, 'GMT+08:00', 28800, 'Asia/Taipei', '8'),
(NULL, 'GMT+03:00', 10800, 'Africa/Dar_es_Salaam', '3'),
(NULL, 'GMT+02:00', 7200, 'Europe/Kiev', '2'),
(NULL, 'GMT+03:00', 10800, 'Europe/Simferopol', '3'),
(NULL, 'GMT+02:00', 7200, 'Europe/Uzhgorod', '2'),
(NULL, 'GMT+02:00', 7200, 'Europe/Zaporozhye', '2'),
(NULL, 'GMT+03:00', 10800, 'Africa/Kampala', '3'),
(NULL, 'GMT-11:00', -39600, 'Pacific/Midway', '-11'),
(NULL, 'GMT+12:00', 43200, 'Pacific/Wake', '12'),
(NULL, 'GMT-10:00', -36000, 'America/Adak', '-10'),
(NULL, 'GMT-09:00', -32400, 'America/Anchorage', '-9'),
(NULL, 'GMT-07:00', -25200, 'America/Boise', '-7'),
(NULL, 'GMT-06:00', -21600, 'America/Chicago', '-6'),
(NULL, 'GMT-07:00', -25200, 'America/Denver', '-7'),
(NULL, 'GMT-05:00', -18000, 'America/Detroit', '-5'),
(NULL, 'GMT-05:00', -18000, 'America/Indiana/Indianapolis', '-5'),
(NULL, 'GMT-06:00', -21600, 'America/Indiana/Knox', '-6'),
(NULL, 'GMT-05:00', -18000, 'America/Indiana/Marengo', '-5'),
(NULL, 'GMT-05:00', -18000, 'America/Indiana/Petersburg', '-5'),
(NULL, 'GMT-06:00', -21600, 'America/Indiana/Tell_City', '-6'),
(NULL, 'GMT-05:00', -18000, 'America/Indiana/Vevay', '-5'),
(NULL, 'GMT-05:00', -18000, 'America/Indiana/Vincennes', '-5'),
(NULL, 'GMT-05:00', -18000, 'America/Indiana/Winamac', '-5'),
(NULL, 'GMT-09:00', -32400, 'America/Juneau', '-9'),
(NULL, 'GMT-05:00', -18000, 'America/Kentucky/Louisville', '-5'),
(NULL, 'GMT-05:00', -18000, 'America/Kentucky/Monticello', '-5'),
(NULL, 'GMT-08:00', -28800, 'America/Los_Angeles', '-8'),
(NULL, 'GMT-06:00', -21600, 'America/Menominee', '-6'),
(NULL, 'GMT-09:00', -32400, 'America/Metlakatla', '-9'),
(NULL, 'GMT-05:00', -18000, 'America/New_York', '-5'),
(NULL, 'GMT-09:00', -32400, 'America/Nome', '-9'),
(NULL, 'GMT-06:00', -21600, 'America/North_Dakota/Beulah', '-6'),
(NULL, 'GMT-06:00', -21600, 'America/North_Dakota/Center', '-6'),
(NULL, 'GMT-06:00', -21600, 'America/North_Dakota/New_Salem', '-6'),
(NULL, 'GMT-07:00', -25200, 'America/Phoenix', '-7'),
(NULL, 'GMT-09:00', -32400, 'America/Sitka', '-9'),
(NULL, 'GMT-09:00', -32400, 'America/Yakutat', '-9'),
(NULL, 'GMT-10:00', -36000, 'Pacific/Honolulu', '-10'),
(NULL, 'GMT-03:00', -10800, 'America/Montevideo', '-3'),
(NULL, 'GMT+05:00', 18000, 'Asia/Samarkand', '5'),
(NULL, 'GMT+05:00', 18000, 'Asia/Tashkent', '5'),
(NULL, 'GMT+01:00', 3600, 'Europe/Vatican', '1'),
(NULL, 'GMT-04:00', -14400, 'America/St_Vincent', '-4'),
(NULL, 'GMT-04:00', -14400, 'America/Caracas', '-4'),
(NULL, 'GMT-04:00', -14400, 'America/Tortola', '-4'),
(NULL, 'GMT-04:00', -14400, 'America/St_Thomas', '-4'),
(NULL, 'GMT+07:00', 25200, 'Asia/Ho_Chi_Minh', '7'),
(NULL, 'GMT+11:00', 39600, 'Pacific/Efate', '11'),
(NULL, 'GMT+12:00', 43200, 'Pacific/Wallis', '12'),
(NULL, 'GMT+14:00', 50400, 'Pacific/Apia', '14'),
(NULL, 'GMT+03:00', 10800, 'Asia/Aden', '3'),
(NULL, 'GMT+03:00', 10800, 'Indian/Mayotte', '3'),
(NULL, 'GMT+02:00', 7200, 'Africa/Johannesburg', '2'),
(NULL, 'GMT+02:00', 7200, 'Africa/Lusaka', '2'),
(NULL, 'GMT+02:00', 7200, 'Africa/Harare', '2');

-- -------------------------------------2021-04-15

UPDATE `default_templates` SET `template` = '<p>Dear #NAME#,</p>\n\n<p>Here is a quick reminder that your current balance is at #BALANCE# which is below your set threshold.</p>\n\n<p>You can refill your account from our website to ensure your services will remain consistent.</p>\n\n<p>For more info, please visit on our website #COMPANY_WEBSITE# or contact to our support at #COMPANY_EMAIL#.</p>\n\n<p>Thanks,<br />\n#COMPANY_NAME#</p>\n' WHERE `name` = 'low_balance';

-- -------------------------------------2021-04-16

INSERT INTO `system` (`name`, `display_name`, `value`, `field_type`, `comment`, `timestamp`, `reseller_id`, `is_display`, `group_title`, `sub_group`, `field_rules`) VALUES ('audit_log', 'Audit Log', '0', 'enable_disable_option', 'You can enable/disable audit logs', '2019-04-01 00:00:00.000000', '0', '0', 'global', 'General', '');

UPDATE `system` SET `display_name` = 'Invoices Older Than Days' WHERE `system`.`name` = "purge_invoices"; 

-- -------------------------------------2021-04-16

DELETE from `system` where `name` = 'paypal_mode';

INSERT INTO `system`(`id`, `name`, `display_name`, `value`, `field_type`, `comment`, `timestamp`, `reseller_id`, `is_display`, `group_title`, `sub_group`, `field_rules`) VALUES (NULL,'paypal_mode','Environment','1','paypal_mode','Set paypal mode. Sandbox for testing','2019-05-24 19:03:37','0','0','payment_methods','Paypal','');

-- -------------------------------------2021-04-19

INSERT INTO `system` ( `name`, `display_name`, `value`, `field_type`, `comment`, `timestamp`, `reseller_id`, `is_display`, `group_title`, `sub_group`, `field_rules`) VALUES
( 'status', 'Status', '1', 'set_status', 'Set enable to activate CDR archive feature', '2019-11-08 19:07:34', 0, 0, 'term_and_condition', '', '');

INSERT INTO `system` ( `name`, `display_name`, `value`, `field_type`, `comment`, `timestamp`, `reseller_id`, `is_display`, `group_title`, `sub_group`, `field_rules`) VALUES
( 'url', 'Url', '1', 'default_system_input', 'Set enable to activate CDR archive feature', '2019-11-08 19:07:34', 0, 0, 'term_and_condition', '', '');

INSERT INTO `system` ( `name`, `display_name`, `value`, `field_type`, `comment`, `timestamp`, `reseller_id`, `is_display`, `group_title`, `sub_group`, `field_rules`) VALUES
( 'text', 'Text', '1', 'textarea', 'Set enable to activate CDR archive feature', '2019-11-08 19:07:34', 0, 0, 'term_and_condition', '', '');

-- -------------------------------------2021-04-19

INSERT INTO `menu_modules` (`menu_label`, `module_name`, `module_url`, `menu_title`, `menu_image`, `menu_subtitle`, `priority`) VALUES
('Low Balance', 'low_balance', 'low_balance/low_balance_list/', 'Reports', '', '0', 89.3);
update userlevels set module_permissions = concat( module_permissions, ',', ( SELECT max(id ) FROM menu_modules ) ) WHERE userlevelid = -1;

INSERT INTO `roles_and_permission` (`id`, `login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES
(NULL, 0, 0, 'reports','low_balance',' ','low_balance_list', 'Low Balance', '["main","list","search"]', 0, '2019-01-25 09:01:03', '7.80000');
UPDATE userlevels SET module_permissions = concat( module_permissions, ',', ( SELECT max( id ) FROM menu_modules WHERE module_url = 'low_balance/low_balance_list/' ) ) WHERE userlevelid = 2;

-- -------------------------------------2021-04-20

ALTER TABLE `trunks` ADD `localization_id` INT NOT NULL;

ALTER TABLE `localization` ADD `dst_base_cid` varchar(200) NOT NULL AFTER `modified_date`, ADD `custom_rule` VARCHAR(200) NOT NULL AFTER `dst_base_cid`;

INSERT INTO `translations` (`id`, `module_name`, `en_En`) VALUES (NULL,'Asia/Dubai','Asia/Dubai'),
(NULL,'Europe/Andorra','Europe/Andorra'),
(NULL,'Asia/Kabul','Asia/Kabul'), 
(NULL,'America/Antigua','America/Antigua'),
(NULL,'America/Anguilla','America/Anguilla'),
(NULL,'Europe/Tirane','Europe/Tirane'),
(NULL,'Asia/Yerevan','Asia/Yerevan'),
(NULL,'Africa/Luanda','Africa/Luanda'),
(NULL,'Antarctica/Casey','Antarctica/Casey'),
(NULL,'Antarctica/Davis','Antarctica/Davis'),
(NULL,'Antarctica/DumontDUrville','Antarctica/DumontDUrville'),
(NULL,'Antarctica/Mawson','Antarctica/Mawson'),
(NULL,'Antarctica/McMurdo','Antarctica/McMurdo'),
(NULL,'Antarctica/Palmer','Antarctica/Palmer'),
(NULL,'Antarctica/Rothera','Antarctica/Rothera'),
(NULL,'Antarctica/Syowa','Antarctica/Syowa'),
(NULL,'Antarctica/Troll','Antarctica/Troll'),
(NULL,'Antarctica/Vostok','Antarctica/Vostok'),
(NULL,'America/Argentina/Buenos_Aires','America/Argentina/Buenos_Aires'),
(NULL,'America/Argentina/Catamarca','America/Argentina/Catamarca'),
(NULL,'America/Argentina/Cordoba','America/Argentina/Cordoba'),
(NULL,'America/Argentina/Jujuy','America/Argentina/Jujuy'),
(NULL,'America/Argentina/La_Rioja','America/Argentina/La_Rioja'),
(NULL,'America/Argentina/Mendoza','America/Argentina/Mendoza'),
(NULL,'America/Argentina/Rio_Gallegos','America/Argentina/Rio_Gallegos'),
(NULL,'America/Argentina/Salta','America/Argentina/Salta'),
(NULL,'America/Argentina/San_Juan','America/Argentina/San_Juan'),
(NULL,'America/Argentina/San_Luis','America/Argentina/San_Luis'),
(NULL,'America/Argentina/Tucuman','America/Argentina/Tucuman'),
(NULL,'America/Argentina/Ushuaia','America/Argentina/Ushuaia'),
(NULL,'Pacific/Pago_Pago','Pacific/Pago_Pago'),
(NULL,'Europe/Vienna','Europe/Vienna'),
(NULL,'Antarctica/Macquarie','Antarctica/Macquarie'),
(NULL,'Australia/Adelaide','Australia/Adelaide'),
(NULL,'Australia/Brisbane','Australia/Brisbane'),
(NULL,'Australia/Broken_Hill','Australia/Broken_Hill'),
(NULL,'Australia/Currie','Australia/Currie'),
(NULL,'Australia/Darwin','Australia/Darwin'),
(NULL,'Australia/Eucla','Australia/Eucla'),
(NULL,'Australia/Hobart','Australia/Hobart'),
(NULL,'Australia/Lindeman','Australia/Lindeman'),
(NULL,'Australia/Lord_Howe','Australia/Lord_Howe'),
(NULL,'Australia/Melbourne','Australia/Melbourne'),
(NULL,'Australia/Perth','Australia/Perth'),
(NULL,'Australia/Sydney','Australia/Sydney'),
(NULL,'America/Aruba','America/Aruba'),
(NULL,'Europe/Mariehamn','Europe/Mariehamn'),
(NULL,'Asia/Baku','Asia/Baku'),
(NULL,'Europe/Sarajevo','Europe/Sarajevo'),
(NULL,'America/Barbados','America/Barbados'),
(NULL,'Asia/Dhaka','Asia/Dhaka'),
(NULL,'Europe/Brussels','Europe/Brussels'),
(NULL,'Africa/Ouagadougou','Africa/Ouagadougou'),
(NULL,'Europe/Sofia','Europe/Sofia'),
(NULL,'Asia/Bahrain','Asia/Bahrain'),
(NULL,'Africa/Bujumbura','Africa/Bujumbura'),
(NULL,'Africa/Porto-Novo','Africa/Porto-Novo'),
(NULL,'America/St_Barthelemy','America/St_Barthelemy'),
(NULL,'Atlantic/Bermuda','Atlantic/Bermuda'),
(NULL,'Asia/Brunei','Asia/Brunei'),
(NULL,'America/La_Paz','America/La_Paz'),
(NULL,'America/Kralendijk','America/Kralendijk'),
(NULL,'America/Araguaina','America/Araguaina'),
(NULL,'America/Bahia','America/Bahia'),
(NULL,'America/Belem','America/Belem'),
(NULL,'America/Boa_Vista','America/Boa_Vista'),
(NULL,'America/Campo_Grande','America/Campo_Grande'),
(NULL,'America/Cuiaba','America/Cuiaba'),
(NULL,'America/Eirunepe','America/Eirunepe'),
(NULL,'America/Fortaleza','America/Fortaleza'),
(NULL,'America/Maceio','America/Maceio'),
(NULL,'America/Manaus','America/Manaus'),
(NULL,'America/Noronha','America/Noronha'),
(NULL,'America/Porto_Velho','America/Porto_Velho'),
(NULL,'America/Recife','America/Recife'),
(NULL,'America/Rio_Branco','America/Rio_Branco'),
(NULL,'America/Santarem','America/Santarem'),
(NULL,'America/Sao_Paulo','America/Sao_Paulo'),
(NULL,'America/Nassau','America/Nassau'),
(NULL,'Asia/Thimphu','Asia/Thimphu'),
(NULL,'Africa/Gaborone','Africa/Gaborone'),
(NULL,'Europe/Minsk','Europe/Minsk'),
(NULL,'America/Belize','America/Belize'),
(NULL,'America/Atikokan','America/Atikokan'),
(NULL,'America/Blanc-Sablon','America/Blanc-Sablon'),
(NULL,'America/Cambridge_Bay','America/Cambridge_Bay'),
(NULL,'America/Creston','America/Creston'),
(NULL,'America/Dawson','America/Dawson'),
(NULL,'America/Dawson_Creek','America/Dawson_Creek'),
(NULL,'America/Edmonton','America/Edmonton'),
(NULL,'America/Fort_Nelson','America/Fort_Nelson'),
(NULL,'America/Glace_Bay','America/Glace_Bay'),
(NULL,'America/Goose_Bay','America/Goose_Bay'),
(NULL,'America/Halifax','America/Halifax'),
(NULL,'America/Inuvik','America/Inuvik'),
(NULL,'America/Iqaluit','America/Iqaluit'),
(NULL,'America/Moncton','America/Moncton'),
(NULL,'America/Nipigon','America/Nipigon'),
(NULL,'America/Pangnirtung','America/Pangnirtung'),
(NULL,'America/Rainy_River','America/Rainy_River'),
(NULL,'America/Rankin_Inlet','America/Rankin_Inlet'),
(NULL,'America/Regina','America/Regina'),
(NULL,'America/Resolute','America/Resolute'),
(NULL,'America/St_Johns','America/St_Johns'),
(NULL,'America/Swift_Current','America/Swift_Current'),
(NULL,'America/Thunder_Bay','America/Thunder_Bay'),
(NULL,'America/Toronto','America/Toronto'),
(NULL,'America/Vancouver','America/Vancouver'),
(NULL,'America/Whitehorse','America/Whitehorse'),
(NULL,'America/Winnipeg','America/Winnipeg'),
(NULL,'America/Yellowknife','America/Yellowknife'),
(NULL,'Indian/Cocos','Indian/Cocos'),
(NULL,'Africa/Kinshasa','Africa/Kinshasa'),
(NULL,'Africa/Lubumbashi','Africa/Lubumbashi'),
(NULL,'Africa/Bangui','Africa/Bangui'),
(NULL,'Africa/Brazzaville','Africa/Brazzaville'),
(NULL,'Europe/Zurich','Europe/Zurich'),
(NULL,'Africa/Abidjan','Africa/Abidjan'),
(NULL,'Pacific/Rarotonga','Pacific/Rarotonga'),
(NULL,'America/Punta_Arenas','America/Punta_Arenas'),
(NULL,'America/Santiago','America/Santiago'),
(NULL,'Pacific/Easter','Pacific/Easter'),
(NULL,'Africa/Douala','Africa/Douala'),
(NULL,'Asia/Shanghai','Asia/Shanghai'),
(NULL,'Asia/Urumqi','Asia/Urumqi'),
(NULL,'America/Bogota','America/Bogota'),
(NULL,'America/Costa_Rica','America/Costa_Rica'),
(NULL,'America/Havana','America/Havana'),
(NULL,'Atlantic/Cape_Verde','Atlantic/Cape_Verde'),
(NULL,'America/Curacao','America/Curacao'),
(NULL,'Indian/Christmas','Indian/Christmas'),
(NULL,'Asia/Famagusta','Asia/Famagusta'),
(NULL,'Asia/Nicosia','Asia/Nicosia'),
(NULL,'Europe/Prague','Europe/Prague'),
(NULL,'Europe/Berlin','Europe/Berlin'),
(NULL,'Europe/Busingen','Europe/Busingen'),
(NULL,'Africa/Djibouti','Africa/Djibouti'),
(NULL,'Europe/Copenhagen','Europe/Copenhagen'),
(NULL,'America/Dominica','America/Dominica'),
(NULL,'America/Santo_Domingo','America/Santo_Domingo'),
(NULL,'Africa/Algiers','Africa/Algiers'),
(NULL,'America/Guayaquil','America/Guayaquil'),
(NULL,'Pacific/Galapagos','Pacific/Galapagos'),
(NULL,'Europe/Tallinn','Europe/Tallinn'),
(NULL,'Africa/Cairo','Africa/Cairo'),
(NULL,'Africa/El_Aaiun','Africa/El_Aaiun'),
(NULL,'Africa/Asmara','Africa/Asmara'),
(NULL,'Africa/Ceuta','Africa/Ceuta'),
(NULL,'Atlantic/Canary','Atlantic/Canary'),
(NULL,'Europe/Madrid','Europe/Madrid'),
(NULL,'Africa/Addis_Ababa','Africa/Addis_Ababa'),
(NULL,'Europe/Helsinki','Europe/Helsinki'),
(NULL,'Pacific/Fiji','Pacific/Fiji'),
(NULL,'Atlantic/Stanley','Atlantic/Stanley'),
(NULL,'Pacific/Chuuk','Pacific/Chuuk'),
(NULL,'Pacific/Kosrae','Pacific/Kosrae'),
(NULL,'Pacific/Pohnpei','Pacific/Pohnpei'),
(NULL,'Atlantic/Faroe','Atlantic/Faroe'),
(NULL,'Europe/Paris','Europe/Paris'),
(NULL,'Africa/Libreville','Africa/Libreville'),
(NULL,'Europe/London','Europe/London'),
(NULL,'America/Grenada','America/Grenada'),
(NULL,'Asia/Tbilisi','Asia/Tbilisi'),
(NULL,'America/Cayenne','America/Cayenne'),
(NULL,'Europe/Guernsey','Europe/Guernsey'),
(NULL,'Africa/Accra','Africa/Accra'),
(NULL,'Europe/Gibraltar','Europe/Gibraltar'),
(NULL,'America/Danmarkshavn','America/Danmarkshavn'),
(NULL,'America/Nuuk','America/Nuuk'),
(NULL,'America/Scoresbysund','America/Scoresbysund'),
(NULL,'America/Thule','America/Thule'),
(NULL,'Africa/Banjul','Africa/Banjul'),
(NULL,'Africa/Conakry','Africa/Conakry'),
(NULL,'America/Guadeloupe','America/Guadeloupe'),
(NULL,'Africa/Malabo','Africa/Malabo'),
(NULL,'Europe/Athens','Europe/Athens'),
(NULL,'Atlantic/South_Georgia','Atlantic/South_Georgia'),
(NULL,'America/Guatemala','America/Guatemala'),
(NULL,'Pacific/Guam','Pacific/Guam'),
(NULL,'Africa/Bissau','Africa/Bissau'),
(NULL,'America/Guyana','America/Guyana'),
(NULL,'Asia/Hong_Kong','Asia/Hong_Kong'),
(NULL,'America/Tegucigalpa','America/Tegucigalpa'),
(NULL,'Europe/Zagreb','Europe/Zagreb'),
(NULL,'America/Port-au-Prince','America/Port-au-Prince'),
(NULL,'Europe/Budapest','Europe/Budapest'),
(NULL,'Asia/Jakarta','Asia/Jakarta'),
(NULL,'Asia/Jayapura','Asia/Jayapura'),
(NULL,'Asia/Makassar','Asia/Makassar'),
(NULL,'Asia/Pontianak','Asia/Pontianak'),
(NULL,'Europe/Dublin','Europe/Dublin'),
(NULL,'Asia/Jerusalem','Asia/Jerusalem'),
(NULL,'Europe/Isle_of_Man','Europe/Isle_of_Man'),
(NULL,'Asia/Kolkata','Asia/Kolkata'),
(NULL,'Indian/Chagos','Indian/Chagos'),
(NULL,'Asia/Baghdad','Asia/Baghdad'),
(NULL,'Asia/Tehran','Asia/Tehran'),
(NULL,'Atlantic/Reykjavik','Atlantic/Reykjavik'),
(NULL,'Europe/Rome','Europe/Rome'),
(NULL,'Europe/Jersey','Europe/Jersey'),
(NULL,'America/Jamaica','America/Jamaica'),
(NULL,'Asia/Amman','Asia/Amman'),
(NULL,'Asia/Tokyo','Asia/Tokyo'),
(NULL,'Africa/Nairobi','Africa/Nairobi'),
(NULL,'Asia/Bishkek','Asia/Bishkek'),
(NULL,'Asia/Phnom_Penh','Asia/Phnom_Penh'),
(NULL,'Pacific/Enderbury','Pacific/Enderbury'),
(NULL,'Pacific/Kiritimati','Pacific/Kiritimati'),
(NULL,'Pacific/Tarawa','Pacific/Tarawa'),
(NULL,'Indian/Comoro','Indian/Comoro'),
(NULL,'America/St_Kitts','America/St_Kitts'),
(NULL,'Asia/Pyongyang','Asia/Pyongyang'),
(NULL,'Asia/Seoul','Asia/Seoul'),
(NULL,'Asia/Kuwait','Asia/Kuwait'),
(NULL,'America/Cayman','America/Cayman'),
(NULL,'Asia/Almaty','Asia/Almaty'),
(NULL,'Asia/Aqtau','Asia/Aqtau'),
(NULL,'Asia/Aqtobe','Asia/Aqtobe'),
(NULL,'Asia/Atyrau','Asia/Atyrau'),
(NULL,'Asia/Oral','Asia/Oral'),
(NULL,'Asia/Qostanay','Asia/Qostanay'),
(NULL,'Asia/Qyzylorda','Asia/Qyzylorda'),
(NULL,'Asia/Vientiane','Asia/Vientiane'),
(NULL,'Asia/Beirut','Asia/Beirut'),
(NULL,'America/St_Lucia','America/St_Lucia'),
(NULL,'Europe/Vaduz','Europe/Vaduz'),
(NULL,'Asia/Colombo','Asia/Colombo'),
(NULL,'Africa/Monrovia','Africa/Monrovia'),
(NULL,'Africa/Maseru','Africa/Maseru'),
(NULL,'Europe/Vilnius','Europe/Vilnius'),
(NULL,'Europe/Luxembourg','Europe/Luxembourg'),
(NULL,'Europe/Riga','Europe/Riga'),
(NULL,'Africa/Tripoli','Africa/Tripoli'),
(NULL,'Africa/Casablanca','Africa/Casablanca'),
(NULL,'Europe/Monaco','Europe/Monaco'),
(NULL,'Europe/Chisinau','Europe/Chisinau'),
(NULL,'Europe/Podgorica','Europe/Podgorica'),
(NULL,'America/Marigot','America/Marigot'),
(NULL,'Indian/Antananarivo','Indian/Antananarivo'),
(NULL,'Pacific/Kwajalein','Pacific/Kwajalein'),
(NULL,'Pacific/Majuro','Pacific/Majuro'),
(NULL,'Europe/Skopje','Europe/Skopje'),
(NULL,'Africa/Bamako','Africa/Bamako'),
(NULL,'Asia/Yangon','Asia/Yangon'),
(NULL,'Asia/Choibalsan','Asia/Choibalsan'),
(NULL,'Asia/Hovd','Asia/Hovd'),
(NULL,'Asia/Ulaanbaatar','Asia/Ulaanbaatar'),
(NULL,'Asia/Macau','Asia/Macau'),
(NULL,'Pacific/Saipan','Pacific/Saipan'),
(NULL,'America/Martinique','America/Martinique'),
(NULL,'Africa/Nouakchott','Africa/Nouakchott'),
(NULL,'America/Montserrat','America/Montserrat'),
(NULL,'Europe/Malta','Europe/Malta'),
(NULL,'Indian/Mauritius','Indian/Mauritius'),
(NULL,'Indian/Maldives','Indian/Maldives'),
(NULL,'Africa/Blantyre','Africa/Blantyre'),
(NULL,'America/Bahia_Banderas','America/Bahia_Banderas'),
(NULL,'America/Cancun','America/Cancun'),
(NULL,'America/Chihuahua','America/Chihuahua'),
(NULL,'America/Hermosillo','America/Hermosillo'),
(NULL,'America/Matamoros','America/Matamoros'),
(NULL,'America/Mazatlan','America/Mazatlan'),
(NULL,'America/Merida','America/Merida'),
(NULL,'America/Mexico_City','America/Mexico_City'),
(NULL,'America/Monterrey','America/Monterrey'),
(NULL,'America/Ojinaga','America/Ojinaga'),
(NULL,'America/Tijuana','America/Tijuana'),
(NULL,'Asia/Kuala_Lumpur','Asia/Kuala_Lumpur'),
(NULL,'Asia/Kuching','Asia/Kuching'),
(NULL,'Africa/Maputo','Africa/Maputo'),
(NULL,'Africa/Windhoek','Africa/Windhoek'),
(NULL,'Pacific/Noumea','Pacific/Noumea'),
(NULL,'Africa/Niamey','Africa/Niamey'),
(NULL,'Pacific/Norfolk','Pacific/Norfolk'),
(NULL,'Africa/Lagos','Africa/Lagos'),
(NULL,'America/Managua','America/Managua'),
(NULL,'Europe/Amsterdam','Europe/Amsterdam'),
(NULL,'Europe/Oslo','Europe/Oslo'),
(NULL,'Asia/Kathmandu','Asia/Kathmandu'),
(NULL,'Pacific/Nauru','Pacific/Nauru'),
(NULL,'Pacific/Niue','Pacific/Niue'),
(NULL,'Pacific/Auckland','Pacific/Auckland'),
(NULL,'Pacific/Chatham','Pacific/Chatham'),
(NULL,'Asia/Muscat','Asia/Muscat'),
(NULL,'America/Panama','America/Panama'),
(NULL,'America/Lima','America/Lima'),
(NULL,'Pacific/Gambier','Pacific/Gambier'),
(NULL,'Pacific/Marquesas','Pacific/Marquesas'),
(NULL,'Pacific/Tahiti','Pacific/Tahiti'),
(NULL,'Pacific/Bougainville','Pacific/Bougainville'),
(NULL,'Pacific/Port_Moresby','Pacific/Port_Moresby'),
(NULL,'Asia/Manila','Asia/Manila'),
(NULL,'Asia/Karachi','Asia/Karachi'),
(NULL,'Europe/Warsaw','Europe/Warsaw'),
(NULL,'America/Miquelon','America/Miquelon'),
(NULL,'Pacific/Pitcairn','Pacific/Pitcairn'),
(NULL,'America/Puerto_Rico','America/Puerto_Rico'),
(NULL,'Asia/Gaza','Asia/Gaza'),
(NULL,'Asia/Hebron','Asia/Hebron'),
(NULL,'Atlantic/Azores','Atlantic/Azores'),
(NULL,'Atlantic/Madeira','Atlantic/Madeira'),
(NULL,'Europe/Lisbon','Europe/Lisbon'),
(NULL,'Pacific/Palau','Pacific/Palau'),
(NULL,'America/Asuncion','America/Asuncion'),
(NULL,'Asia/Qatar','Asia/Qatar'),
(NULL,'Indian/Reunion','Indian/Reunion'),
(NULL,'Europe/Bucharest','Europe/Bucharest'),
(NULL,'Europe/Belgrade','Europe/Belgrade'),
(NULL,'Asia/Anadyr','Asia/Anadyr'),
(NULL,'Asia/Barnaul','Asia/Barnaul'),
(NULL,'Asia/Chita','Asia/Chita'),
(NULL,'Asia/Irkutsk','Asia/Irkutsk'),
(NULL,'Asia/Kamchatka','Asia/Kamchatka'),
(NULL,'Asia/Khandyga','Asia/Khandyga'),
(NULL,'Asia/Krasnoyarsk','Asia/Krasnoyarsk'),
(NULL,'Asia/Magadan','Asia/Magadan'),
(NULL,'Asia/Novokuznetsk','Asia/Novokuznetsk'),
(NULL,'Asia/Novosibirsk','Asia/Novosibirsk'),
(NULL,'Asia/Omsk','Asia/Omsk'),
(NULL,'Asia/Sakhalin','Asia/Sakhalin'),
(NULL,'Asia/Srednekolymsk','Asia/Srednekolymsk'),
(NULL,'Asia/Tomsk','Asia/Tomsk'),
(NULL,'Asia/Ust-Nera','Asia/Ust-Nera'),
(NULL,'Asia/Vladivostok','Asia/Vladivostok'),
(NULL,'Asia/Yakutsk','Asia/Yakutsk'),
(NULL,'Asia/Yekaterinburg','Asia/Yekaterinburg'),
(NULL,'Europe/Astrakhan','Europe/Astrakhan'),
(NULL,'Europe/Kaliningrad','Europe/Kaliningrad'),
(NULL,'Europe/Kirov','Europe/Kirov'),
(NULL,'Europe/Moscow','Europe/Moscow'),
(NULL,'Europe/Samara','Europe/Samara'),
(NULL,'Europe/Saratov','Europe/Saratov'),
(NULL,'Europe/Ulyanovsk','Europe/Ulyanovsk'),
(NULL,'Europe/Volgograd','Europe/Volgograd'),
(NULL,'Africa/Kigali','Africa/Kigali'),
(NULL,'Asia/Riyadh','Asia/Riyadh'),
(NULL,'Pacific/Guadalcanal','Pacific/Guadalcanal'),
(NULL,'Indian/Mahe','Indian/Mahe'),
(NULL,'Africa/Khartoum','Africa/Khartoum'),
(NULL,'Europe/Stockholm','Europe/Stockholm'),
(NULL,'Asia/Singapore','Asia/Singapore'),
(NULL,'Atlantic/St_Helena','Atlantic/St_Helena'),
(NULL,'Europe/Ljubljana','Europe/Ljubljana'),
(NULL,'Arctic/Longyearbyen','Arctic/Longyearbyen'),
(NULL,'Europe/Bratislava','Europe/Bratislava'),
(NULL,'Africa/Freetown','Africa/Freetown'),
(NULL,'Europe/San_Marino','Europe/San_Marino'),
(NULL,'Africa/Dakar','Africa/Dakar'),
(NULL,'Africa/Mogadishu','Africa/Mogadishu'),
(NULL,'America/Paramaribo','America/Paramaribo'),
(NULL,'Africa/Juba','Africa/Juba'),
(NULL,'Africa/Sao_Tome','Africa/Sao_Tome'),
(NULL,'America/El_Salvador','America/El_Salvador'),
(NULL,'America/Lower_Princes','America/Lower_Princes'),
(NULL,'Asia/Damascus','Asia/Damascus'),
(NULL,'Africa/Mbabane','Africa/Mbabane'),
(NULL,'America/Grand_Turk','America/Grand_Turk'),
(NULL,'Africa/Ndjamena','Africa/Ndjamena'),
(NULL,'Indian/Kerguelen','Indian/Kerguelen'),
(NULL,'Africa/Lome','Africa/Lome'),
(NULL,'Asia/Bangkok','Asia/Bangkok'),
(NULL,'Asia/Dushanbe','Asia/Dushanbe'),
(NULL,'Pacific/Fakaofo','Pacific/Fakaofo'),
(NULL,'Asia/Dili','Asia/Dili'),
(NULL,'Asia/Ashgabat','Asia/Ashgabat'),
(NULL,'Africa/Tunis','Africa/Tunis'),
(NULL,'Pacific/Tongatapu','Pacific/Tongatapu'),
(NULL,'Europe/Istanbul','Europe/Istanbul'),
(NULL,'America/Port_of_Spain','America/Port_of_Spain'),
(NULL,'Pacific/Funafuti','Pacific/Funafuti'),
(NULL,'Asia/Taipei','Asia/Taipei'),
(NULL,'Africa/Dar_es_Salaam','Africa/Dar_es_Salaam'),
(NULL,'Europe/Kiev','Europe/Kiev'),
(NULL,'Europe/Simferopol','Europe/Simferopol'),
(NULL,'Europe/Uzhgorod','Europe/Uzhgorod'),
(NULL,'Europe/Zaporozhye','Europe/Zaporozhye'),
(NULL,'Africa/Kampala','Africa/Kampala'),
(NULL,'Pacific/Midway','Pacific/Midway'),
(NULL,'Pacific/Wake','Pacific/Wake'),
(NULL,'America/Adak','America/Adak'),
(NULL,'America/Anchorage','America/Anchorage'),
(NULL,'America/Boise','America/Boise'),
(NULL,'America/Chicago','America/Chicago'),
(NULL,'America/Denver','America/Denver'),
(NULL,'America/Detroit','America/Detroit'),
(NULL,'America/Indiana/Indianapolis','America/Indiana/Indianapolis'),
(NULL,'America/Indiana/Knox','America/Indiana/Knox'),
(NULL,'America/Indiana/Marengo','America/Indiana/Marengo'),
(NULL,'America/Indiana/Petersburg','America/Indiana/Petersburg'),
(NULL,'America/Indiana/Tell_City','America/Indiana/Tell_City'),
(NULL,'America/Indiana/Vevay','America/Indiana/Vevay'),
(NULL,'America/Indiana/Vincennes','America/Indiana/Vincennes'),
(NULL,'America/Indiana/Winamac','America/Indiana/Winamac'),
(NULL,'America/Juneau','America/Juneau'),
(NULL,'America/Kentucky/Louisville','America/Kentucky/Louisville'),
(NULL,'America/Kentucky/Monticello','America/Kentucky/Monticello'),
(NULL,'America/Los_Angeles','America/Los_Angeles'),
(NULL,'America/Menominee','America/Menominee'),
(NULL,'America/Metlakatla','America/Metlakatla'),
(NULL,'America/New_York','America/New_York'),
(NULL,'America/Nome','America/Nome'),
(NULL,'America/North_Dakota/Beulah','America/North_Dakota/Beulah'),
(NULL,'America/North_Dakota/Center','America/North_Dakota/Center'),
(NULL,'America/North_Dakota/New_Salem','America/North_Dakota/New_Salem'),
(NULL,'America/Phoenix','America/Phoenix'),
(NULL,'America/Sitka','America/Sitka'),
(NULL,'America/Yakutat','America/Yakutat'),
(NULL,'Pacific/Honolulu','Pacific/Honolulu'),
(NULL,'America/Montevideo','America/Montevideo'),
(NULL,'Asia/Samarkand','Asia/Samarkand'),
(NULL,'Asia/Tashkent','Asia/Tashkent'),
(NULL,'Europe/Vatican','Europe/Vatican'),
(NULL,'America/St_Vincent','America/St_Vincent'),
(NULL,'America/Caracas','America/Caracas'),
(NULL,'America/Tortola','America/Tortola'),
(NULL,'America/St_Thomas','America/St_Thomas'),
(NULL,'Asia/Ho_Chi_Minh','Asia/Ho_Chi_Minh'),
(NULL,'Pacific/Efate','Pacific/Efate'),
(NULL,'Pacific/Wallis','Pacific/Wallis'),
(NULL,'Pacific/Apia','Pacific/Apia'),
(NULL,'Asia/Aden','Asia/Aden'),
(NULL,'Indian/Mayotte','Indian/Mayotte'),
(NULL,'Africa/Johannesburg','Africa/Johannesburg'),
(NULL,'Africa/Lusaka','Africa/Lusaka'),
(NULL,'Africa/Harare','Africa/Harare'),
(NULL,'Low Balance','Low Balance'),
(NULL,'Trunk Statistics','Trunk Statistics'),
(NULL,'Current Balance','Current Balance'),
(NULL,'Emails','Emails'),
(NULL,'Add IP Settings','Add IP Settings'),
(NULL,'Edit IP Settings','Edit IP Settings'),
(NULL,'Edit Caller ID','Edit Caller ID'),
(NULL,'Invoice Date Interval','Invoice Date Interval'),
(NULL,'Use same credential for Invoice Config','Use same credential for Invoice Config'),
(NULL,'Registration URL','Registration URL'),
(NULL,'Account Status','Account Status'),
(NULL,'Admin','Admin'),
(NULL,'Edit Accessnumber','Edit Accessnumber'),
(NULL,'Edit Rate Group','Edit Rate Group'),
(NULL,'Percentage (Enterprise)','Percentage (Enterprise)'),
(NULL,'Edit Ratedeck','Edit Ratedeck'),
(NULL,'Realm','Realm'),
(NULL,'Reg-Transport','Reg-Transport'),
(NULL,'Failover','Failover'),
(NULL,'GW Name #1','GW Name #1'),
(NULL,'GW Name #2','GW Name #2'),
(NULL,'Gateway','Gateway'),
(NULL,'Count','Count'),
(NULL,'Both','Both'),
(NULL,'Stop','Stop'),
(NULL,'Reload','Reload'),
(NULL,'Rescan','Rescan'),
(NULL,'Org.','Org.'),
(NULL,'Read','Read'),
(NULL,'Write','Write');

INSERT INTO `translations` (`id`, `module_name`, `en_En`) VALUES
(NULL,'STANDARD','STANDARD'),
(NULL,'CALLINGCARD','CALLINGCARD'),
(NULL,'FREE','FREE'),
(NULL,'LOCAL','LOCAL'),
(NULL,'ACCOUNT_INACTIVE_DELETED','ACCOUNT_INACTIVE_DELETED'),
(NULL,'ACCOUNT_EXPIRE','ACCOUNT_EXPIRE'),
(NULL,'ALLOTTED_TIMEOUT','ALLOTTED_TIMEOUT'),
(NULL,'AUTHENTICATION_FAIL','AUTHENTICATION_FAIL'),
(NULL,'BEARERCAPABILITY_NOTAUTH','BEARERCAPABILITY_NOTAUTH'),
(NULL,'BEARERCAPABILITY_NOTAVAIL','BEARERCAPABILITY_NOTAVAIL'),
(NULL,'BEARERCAPABILITY_NOTIMPL','BEARERCAPABILITY_NOTIMPL'),
(NULL,'CALL_REJECTED','CALL_REJECTED'),
(NULL,'CHAN_NOT_IMPLEMENTED','CHAN_NOT_IMPLEMENTED'),
(NULL,'CHANNEL_UNACCEPTABLE','CHANNEL_UNACCEPTABLE'),
(NULL,'DESTINATION_OUT_OF_ORDER','DESTINATION_OUT_OF_ORDER'),
(NULL,'DESTINATION_BLOCKED','DESTINATION_BLOCKED'),
(NULL,'DID_DESTINATION_NOT_FOUND','DID_DESTINATION_NOT_FOUND'),
(NULL,'FACILITY_REJECTED','FACILITY_REJECTED'),
(NULL,'FACILITY_NOT_SUBSCRIBED','FACILITY_NOT_SUBSCRIBED'),
(NULL,'FACILITY_NOT_IMPLEMENTED','FACILITY_NOT_IMPLEMENTED'),
(NULL,'FRAUD_CALL_PER_ACCOUNT','FRAUD_CALL_PER_ACCOUNT'),
(NULL,'FRAUD_CALL_PER_DESTINATION','FRAUD_CALL_PER_DESTINATION'),
(NULL,'FRAUD_COST_PER_ACCOUNT','FRAUD_COST_PER_ACCOUNT'),
(NULL,'FRAUD_COST_PER_DESTINATION','FRAUD_COST_PER_DESTINATION'),
(NULL,'INVALID_NUMBER_FORMAT','INVALID_NUMBER_FORMAT'),
(NULL,'INCOMPATIBLE_DESTINATION','INCOMPATIBLE_DESTINATION'),
(NULL,'MANAGER_REQUEST','MANAGER_REQUEST'),
(NULL,'MEDIA_TIMEOUT','MEDIA_TIMEOUT'),
(NULL,'NO_ROUTE_DESTINATION','NO_ROUTE_DESTINATION'),
(NULL,'NORMAL_CLEARING','NORMAL_CLEARING'),
(NULL,'NETWORK_OUT_OF_ORDER','NETWORK_OUT_OF_ORDER'),
(NULL,'NORMAL_UNSPECIFIED','NORMAL_UNSPECIFIED'),
(NULL,'NORMAL_CIRCUIT_CONGESTION','NORMAL_CIRCUIT_CONGESTION'),
(NULL,'NORMAL_TEMPORARY_FAILURE','NORMAL_TEMPORARY_FAILURE'),
(NULL,'NO_SUFFICIENT_FUND','NO_SUFFICIENT_FUND'),
(NULL,'NO_USER_RESPONSE','NO_USER_RESPONSE'),
(NULL,'NO_ANSWER','NO_ANSWER'),
(NULL,'NUMBER_CHANGED','NUMBER_CHANGED'),
(NULL,'ORIGINATOR_CANCEL','ORIGINATOR_CANCEL'),
(NULL,'ORIGNATION_RATE_NOT_FOUND','ORIGNATION_RATE_NOT_FOUND'),
(NULL,'OUTGOING_CALL_BARRED','OUTGOING_CALL_BARRED'),
(NULL,'PROGRESS_TIMEOUT','PROGRESS_TIMEOUT'),
(NULL,'RECOVERY_ON_TIMER_EXPIRE','RECOVERY_ON_TIMER_EXPIRE'),
(NULL,'RESELLER_COST_CHEAP','RESELLER_COST_CHEAP'),
(NULL,'SERVICE_NOT_IMPLEMENTED','SERVICE_NOT_IMPLEMENTED'),
(NULL,'SERVICE_UNAVAILABLE','SERVICE_UNAVAILABLE'),
(NULL,'SUCCESS','SUCCESS'),
(NULL,'SWITCH_CONGESTION','SWITCH_CONGESTION'),
(NULL,'TERMINATION_RATE_NOT_FOUND','TERMINATION_RATE_NOT_FOUND'),
(NULL,'UNSPECIFIED','UNSPECIFIED'),
(NULL,'UNALLOCATED_NUMBER','UNALLOCATED_NUMBER'),
(NULL,'USER_BUSY','USER_BUSY'),
(NULL,'USER_NOT_REGISTERED','USER_NOT_REGISTERED'),
(NULL,'REQUESTED_CHAN_UNAVAIL','REQUESTED_CHAN_UNAVAIL'),
(NULL,'Resend Email','Resend Email'),
(NULL,'Resent Email','Resent Email'),
(NULL,'Sent','Sent'),
(NULL,'Account Number Editable','Account Number Editable'),
(NULL,'Play Audio Notifications','Play Audio Notifications'),
(NULL,'Invoices Older Than Days','Invoices Older Than Days'),
(NULL,'Half Year','Half Year');
-- -------------------------------------2021-04-21

UPDATE userlevels SET module_permissions = concat( module_permissions, ',', (  SELECT max( id ) FROM menu_modules WHERE module_url = 'accounts/admin_list/' ) ) WHERE userlevelid = 2;

UPDATE userlevels SET module_permissions = concat( module_permissions, ',', (  SELECT max( id ) FROM menu_modules WHERE module_url = 'permissions/permissions_list/' ) ) WHERE userlevelid = 2;

UPDATE userlevels SET module_permissions = concat( module_permissions, ',', (  SELECT max( id ) FROM menu_modules WHERE module_url = 'ipmap/ipmap_detail/' ) ) WHERE userlevelid = 2;

UPDATE userlevels SET module_permissions = concat( module_permissions, ',', (  SELECT max( id ) FROM menu_modules WHERE module_url = 'animap/animap_detail/' ) ) WHERE userlevelid = 2;

UPDATE `roles_and_permission` SET `permissions` = '[\"main\",\"list\",\"new\",\"edit\",\"search\"]' WHERE `module_name` = 'orders' AND `module_url` = 'orders_list';

UPDATE `roles_and_permission` SET `permissions` = '[\"main\",\"list\"]' WHERE `login_type` = 0 AND `menu_name` = 'configuration' AND `module_url` = 'invoice_conf_list';

UPDATE `roles_and_permission` SET `permissions` = '[\"main\",\"list\",\"edit\"]' WHERE `login_type` = 1 AND `menu_name` = 'configuration' AND `module_url` = 'invoice_conf_list';

-- -------------------------------------2021-04-21

ALTER TABLE `reseller_cdrs` ADD `trunk_id` INT NOT NULL;

-- -------------------------------------2021-04-22
-- ALTER TABLE `mail_details` DROP COLUMN `cc`;

-- ALTER TABLE `mail_details`  ADD `cc` varchar(255) NULL;

INSERT INTO `cron_settings` (`name`, `command`, `exec_interval`, `creation_date`, `last_modified_date`, `last_execution_date`, `next_execution_date`, `status`, `file_path`) VALUES ( 'Currency Update', 'days', '1', UTC_TIMESTAMP(), UTC_TIMESTAMP(),'0000-00-00 00:00:00','0000-00-00 00:00:00', '0', 'wget --no-check-certificate -q -O- {BASE_URL}currencyupdate/update_currency/');

-- -------------------------------------2021-04-21

DELETE FROM `menu_modules` WHERE `module_url` = 'freeswitch/fsserver_list/';

DELETE FROM `menu_modules` WHERE `module_url` = 'reports/charges_history/';

DELETE FROM `menu_modules` WHERE `module_url` = 'user/user_charges_history/';

DELETE FROM `roles_and_permission` WHERE `module_url` = 'charges_history';

-- ------------------------------------2021-04-22

INSERT INTO `translations` (`id`, `module_name`, `en_En`) VALUES
(NULL,'Last Pay Date','Last Pay Date'),
(NULL,'Buy DIDs','Buy DIDs'),
(NULL,'Purchased DID','Purchased DID'),
(NULL,'DID Information','DID Information'),
(NULL,'Sell Cost','Sell Cost'),
(NULL,'Admin Rate Group','Admin Rate Group'),
(NULL,'Search My Rates','Search My Rates'),
(NULL,'Optin','Optin'),
(NULL,'Bal','Bal'),
(NULL,'Managed & Maintained by','Managed & Maintained by'),
(NULL,'iNextrix Technologies Pvt. Ltd.','iNextrix Technologies Pvt. Ltd.'),
(NULL,'All Rights Reserved.','All Rights Reserved.'),
(NULL,'module_name','module_name'),
(NULL,'English','English'),
(NULL,'Chinese','Chinese'),
(NULL,'French','French'),
(NULL,'German','German'),
(NULL,'Greek','Greek'),
(NULL,'Italian','Italian'),
(NULL,'Spanish','Spanish'),
(NULL,'Russian','Russian'),
(NULL,'Japanese','Japanese'),
(NULL,'Portuguese','Portuguese'),
(NULL,'Romanian','Romanian'),
(NULL,'Create Translation Languages','Create Translation Languages'),
(NULL,'Module Name','Module Name'),
(NULL,'Edit Translation Language','Edit Translation Language');


UPDATE `translations` SET `module_name`='Page ', `en_En` = 'Page ' where `module_name`='Page';
UPDATE `translations` SET `module_name`=' of ', `en_En` = ' of ' where `module_name`='of';
UPDATE `translations` SET `module_name`=' Records', `en_En` = ' Records' where `module_name`='Records';
UPDATE `translations` SET `module_name`="Todays Calls", `en_En` = "Todays Calls" where `module_name`="Today's Calls";
-- -------------------------------------2021-04-23

DELETE FROM `roles_and_permission` WHERE `menu_name` = 'inbound' AND `module_name` = 'local_number';

UPDATE userlevels SET module_permissions = concat( module_permissions, ',', (  SELECT max(id ) FROM menu_modules WHERE menu_title = 
'Inbound' AND module_url = 'accessnumber/accessnumber_list/' ) ) WHERE userlevelid = 2;

UPDATE `roles_and_permission` SET `permissions` = '[\"main\",\"list\",\"create\",\"export\",\"import\",\"delete\",\"edit\",\"search\"]' WHERE `login_type` = 0 AND `module_url` = 'accessnumber_list';


-- --------------------------------------2021-04-24

ALTER TABLE `currency` ADD `is_supported` TINYINT(1) NOT NULL DEFAULT '1' AFTER `last_updated`;

UPDATE `currency` SET `is_supported` = '0' WHERE `currency` in ('AUD','BRL','CAD','CNY','CZK','DKK','EUR','HKD','HUF','ILS','JPY','MYR','MXN','TWD','NZD','NOK','PHP','PLN','GBP','RUB','SGD','SEK','CHF','THB','USD');

-- -------------------------------------2021-04-23

UPDATE `default_templates` SET `name` = 'balance_transfer' WHERE `name` = 'balance_tranfer';

-- -------------------------------------2021-04-27

UPDATE userlevels SET module_permissions = concat( module_permissions, ',', (  SELECT max( id ) FROM menu_modules WHERE module_url = 'summary/product/' ) ) WHERE userlevelid = 2;

DELETE FROM `roles_and_permission` WHERE `module_name` = 'email' AND `module_url` = 'email_mass';

-- -------------------------------------2021-04-27


INSERT INTO `roles_and_permission` (`id`, `login_type`, `permission_type`, `menu_name`, `module_name`, `sub_module_name`, `module_url`, `display_name`, `permissions`, `status`, `creation_date`, `priority`) VALUES
(NULL, 0, 0, 'billing','reports',' ','commission_report_list', 'Commission Report', '["main","list","export","search"]', 0, '2019-01-25 09:01:03', '2.30000'); 

UPDATE userlevels SET module_permissions = concat( module_permissions, ',', (  SELECT max( id ) FROM menu_modules WHERE module_url = 'reports/commission_report_list/' ) ) WHERE userlevelid = 2;

-- -------------------------------------2021-04-28

UPDATE `default_templates` SET `subject` = 'Your account password has been reset.' WHERE `name` = 'reset_password';

-- -------------------------------------2021-04-29

UPDATE `default_templates` SET `subject` = '#NAME#, New #PRODUCT_NAME# added to your account #NUMBER#' WHERE `name` = 'product_purchase';

-- --------------------------------------2021-04-30

INSERT INTO `system` (`id`, `name`, `display_name`, `value`, `field_type`, `comment`, `timestamp`, `reseller_id`, `is_display`, `group_title`, `sub_group`, `field_rules`) VALUES (NULL, 'datacoll', 'Datacoll Details', '2021-04-27', 'default_system_input', NULL, '2019-04-01 00:00:00.000000', '', '1', '', '', '');

update `system` set `group_title` = "payment_methods" where name="datacoll";

DELETE from `system` where `name` = 'paypal_status';
INSERT INTO `system` (`id`, `name`, `display_name`, `value`, `field_type`, `comment`, `timestamp`, `reseller_id`, `is_display`, `group_title`, `sub_group`, `field_rules`) VALUES (NULL, 'paypal_status', 'Paypal', '0', 'enable_disable_option', 'Set your paypal status here.', '2019-04-01 00:00:00.000000', '0', '0', 'payment_methods', 'Paypal', '');
update `invoice_conf` set `domain` = 'inextrix.com' where `id` = 1;
delete from `invoice_conf` where `id` = 2;
update `system` set `value` = '5.0' where name="version";



INSERT INTO `translations` (`id`, `module_name`, `en_En`) VALUES
(NULL,'Distributor','Distributor'),
(NULL,'Commission Based','Commission Based'),
(NULL,'Reseller Type','Reseller Type'),
(NULL,'Callerid','Callerid'),
(NULL,'Opensips Dispatcher','Opensips Dispatcher'),
(NULL,'Generate','Generate'),
(NULL,'Forward','Forward'),
(NULL,'Add White List','Add White List'),
(NULL,'Report','Report'),
(NULL,'Profiles','Profiles'),
(NULL,'Create Duplicate Rate Group','Create Duplicate Rate Group'),
(NULL,'Add Timezone','Add Timezone'),
(NULL,'Timezone List','Timezone List'),
(NULL,'GMT Offset','GMT Offset'),
(NULL,'Edit Timezone','Edit Timezone'),
(NULL,'Account Notification','Account Notification'),
(NULL,'Both (Email & SMS)','Both (Email & SMS)'),
(NULL,'Terms & Condition','Terms & Condition'),
(NULL,'Term And Condition','Term And Condition'),
(NULL,'Url','Url'),
(NULL,'Text','Text'),
(NULL,'Custom Rates','Custom Rates'),
(NULL,'(Price+SetUp Fee)','(Price+SetUp Fee)');


-- --------------------------------------2021-05-04

DELETE FROM `roles_and_permission` WHERE `menu_name`= 'switch' AND `module_name`= 'freeswitch' AND `module_url` ='dispatcher_list' AND `login_type` = '0';

DELETE FROM `roles_and_permission` WHERE `menu_name`= 'switch' AND `module_name`= 'fraud_detection' AND `module_url` ='fraud_detection_list' AND `login_type` = '0';

DELETE FROM `roles_and_permission` WHERE `menu_name`= 'switch' AND `module_name`= 'alarm' AND `module_url` ='alert_list' AND `login_type` = '0';

DELETE FROM `roles_and_permission` WHERE `menu_name`= 'switch' AND `module_name`= 'fraud_detection' AND `module_url` ='configuration_add' AND `login_type` = '0';

DELETE FROM `roles_and_permission` WHERE `menu_name`= 'switch' AND `module_name`= 'alarmreport' AND `module_url` ='alarmreport_list' AND `login_type` = '0';

delete from `menu_modules` where `menu_label`='Registered SIP Devices' and `module_name`='sip';

delete from `menu_modules` where `menu_label`='Registered Gateways' and `module_name`='gateways';

delete from `menu_modules` where `menu_label`='Switch CLI' and `module_name`='fs';

delete from `menu_modules` where `menu_label`='Live Call Graph' and `module_name`='live';

delete from `system` where `name` = 'refresh_second';

Alter table `counters` add `type` tinyint(1) NOT NULL;
